export const INDIAN_COLLEGES: string[] = [
  // IITs
  "Indian Institute of Technology (IIT) Bombay",
  "Indian Institute of Technology (IIT) Delhi",
  "Indian Institute of Technology (IIT) Madras",
  "Indian Institute of Technology (IIT) Kharagpur",
  "Indian Institute of Technology (IIT) Kanpur",
  "Indian Institute of Technology (IIT) Roorkee",
  "Indian Institute of Technology (IIT) Guwahati",
  "Indian Institute of Technology (IIT) Hyderabad",
  "Indian Institute of Technology (IIT) BHU Varanasi",
  "Indian Institute of Technology (IIT) Indore",
  "Indian Institute of Technology (IIT) Bhubaneswar",
  "Indian Institute of Technology (IIT) Patna",
  "Indian Institute of Technology (IIT) Gandhinagar",
  "Indian Institute of Technology (IIT) Ropar",
  "Indian Institute of Technology (IIT) Mandi",
  "Indian Institute of Technology (IIT) Jodhpur",
  "Indian Institute of Technology (IIT) Tirupati",
  "Indian Institute of Technology (IIT) Palakkad",
  "Indian Institute of Technology (IIT) Goa",
  "Indian Institute of Technology (IIT) Jammu",
  "Indian Institute of Technology (IIT) Dharwad",
  "Indian Institute of Technology (IIT) Bhilai",

  // NITs
  "National Institute of Technology (NIT) Trichy",
  "National Institute of Technology (NIT) Karnataka, Surathkal",
  "National Institute of Technology (NIT) Rourkera",
  "National Institute of Technology (NIT) Warangal",
  "National Institute of Technology (NIT) Calicut",
  "Visvesvaraya National Institute of Technology (VNIT) Nagpur",
  "National Institute of Technology (NIT) Kurukshetra",
  "National Institute of Technology (NIT) Silchar",
  "National Institute of Technology (NIT) Durgapur",
  "National Institute of Technology (NIT) Jalandhar",
  "Motilal Nehru National Institute of Technology (MNNIT) Allahabad",
  "Malaviya National Institute of Technology (MNIT) Jaipur",
  "Maulana Azad National Institute of Technology (MANIT) Bhopal",
  "Sardar Vallabhbhai National Institute of Technology (SVNIT) Surat",
  "National Institute of Technology (NIT) Raipur",
  "National Institute of Technology (NIT) Patna",
  "National Institute of Technology (NIT) Srinagar",
  "National Institute of Technology (NIT) Agartala",
  "National Institute of Technology (NIT) Goa",
  "National Institute of Technology (NIT) Meghalaya",
  "National Institute of Technology (NIT) Jamshedpur",
  "National Institute of Technology (NIT) Hamirpur",
  "National Institute of Technology (NIT) Uttarakhand",

  // IIITs
  "International Institute of Information Technology (IIIT) Hyderabad",
  "International Institute of Information Technology (IIIT) Bangalore",
  "Indraprastha Institute of Information Technology (IIIT) Delhi",
  "Indian Institute of Information Technology (IIIT) Allahabad",
  "ABV-Indian Institute of Information Technology and Management (IIITM) Gwalior",
  "PDPM Indian Institute of Information Technology, Design and Manufacturing (IIITDM) Jabalpur",
  "Indian Institute of Information Technology, Design and Manufacturing (IIITDM) Kancheepuram",
  "Indian Institute of Information Technology (IIIT) Pune",
  "Indian Institute of Information Technology (IIIT) Nagpur",
  "Indian Institute of Information Technology (IIIT) Lucknow",
  "Indian Institute of Information Technology (IIIT) Dharwad",
  "Indian Institute of Information Technology (IIIT) Kottayam",
  "Indian Institute of Information Technology (IIIT) Sri City",
  "Indian Institute of Information Technology (IIIT) Vadodara",
  "Indian Institute of Information Technology (IIIT) Guwahati",
  "Indian Institute of Information Technology (IIIT) Kota",

  // BITS
  "BITS Pilani - Birla Institute of Technology and Science, Pilani",
  "BITS Pilani - Birla Institute of Technology and Science, Goa",
  "BITS Pilani - Birla Institute of Technology and Science, Hyderabad",

  // Maharashtra
  "College of Engineering, Pune (COEP)",
  "Veermata Jijabai Technological Institute (VJTI), Mumbai",
  "Sardar Patel Institute of Technology (SPIT), Mumbai",
  "Sardar Patel College of Engineering (SPCE), Mumbai",
  "Pune Institute of Computer Technology (PICT), Pune",
  "MIT Academy of Engineering (MITAOE), Pune",
  "MIT World Peace University (MIT-WPU), Pune",
  "Vishwakarma Institute of Technology (VIT), Pune",
  "Vishwakarma Institute of Information Technology (VIIT), Pune",
  "Dwarkadas J. Sanghvi College of Engineering (DJSCE), Mumbai",
  "K. J. Somaiya College of Engineering (KJSCE), Mumbai",
  "Thadomal Shahani Engineering College (TSEC), Mumbai",
  "Fr. Conceicao Rodrigues College of Engineering (CRCE), Mumbai",
  "Walchand College of Engineering, Sangli",
  "Ramdeobaba College of Engineering and Management (RCOEM), Nagpur",
  "D. Y. Patil College of Engineering, Akurdi, Pune",
  "D. Y. Patil Institute of Technology, Pimpri, Pune",
  "G. H. Raisoni College of Engineering, Nagpur",
  "Institute of Chemical Technology (ICT), Mumbai",
  "MKSSS's Cummins College of Engineering for Women, Pune",
  "Government College of Engineering, Karad",
  "Government College of Engineering, Aurangabad",

  // Delhi & NCR
  "Delhi Technological University (DTU), Delhi",
  "Netaji Subhas University of Technology (NSUT), Delhi",
  "Indira Gandhi Delhi Technical University for Women (IGDTUW), Delhi",
  "Guru Gobind Singh Indraprastha University (GGSIPU), Delhi",
  "Maharaja Agrasen Institute of Technology (MAIT), Delhi",
  "Maharaja Surajmal Institute of Technology (MSIT), Delhi",
  "Bharati Vidyapeeth's College of Engineering (BVCOE), Delhi",
  "Jaypee Institute of Information Technology (JIIT), Noida",
  "Amity University, Noida",
  "Amity University, Gurgaon",
  "Galgotias College of Engineering and Technology, Greater Noida",
  "Sharda University, Greater Noida",
  "JSS Academy of Technical Education, Noida",
  "Ajay Kumar Garg Engineering College (AKGEC), Ghaziabad",
  "Kiets Group of Institutions, Ghaziabad",

  // Karnataka
  "RV College of Engineering (RVCE), Bengaluru",
  "PES University, Ring Road Campus, Bengaluru",
  "PES University, Electronic City Campus, Bengaluru",
  "B.M.S. College of Engineering (BMSCE), Bengaluru",
  "M. S. Ramaiah Institute of Technology (MSRIT), Bengaluru",
  "Bangalore Institute of Technology (BIT), Bengaluru",
  "Sri Jayachamarajendra College of Engineering (SJCE), Mysuru",
  "National Institute of Engineering (NIE), Mysuru",
  "Dayananda Sagar College of Engineering (DSCE), Bengaluru",
  "Nitte Meenakshi Institute of Technology (NMIT), Bengaluru",
  "Sir M. Visvesvaraya Institute of Technology (SIR MVI), Bengaluru",
  "Christ University (Faculty of Engineering), Bengaluru",
  "New Horizon College of Engineering, Bengaluru",
  "Alliance University, Bengaluru",

  // Tamil Nadu
  "Vellore Institute of Technology (VIT), Vellore",
  "Vellore Institute of Technology (VIT), Chennai",
  "SRM Institute of Science and Technology, Kattankulathur",
  "SRM Institute of Science and Technology, Ramapuram",
  "PSG College of Technology, Coimbatore",
  "Coimbatore Institute of Technology (CIT), Coimbatore",
  "College of Engineering, Guindy (CEG), Anna University, Chennai",
  "Madras Institute of Technology (MIT), Anna University, Chennai",
  "SSN College of Engineering, Chennai",
  "Sastra Deemed University, Tanjore",
  "Amrita School of Engineering, Coimbatore",
  "Amrita School of Engineering, Chennai",
  "Thiagarajar College of Engineering (TCE), Madurai",
  "Sathyabama Institute of Science and Technology, Chennai",
  "Hindustan Institute of Technology and Science, Chennai",

  // Telangana & Andhra Pradesh
  "Chaitanya Bharathi Institute of Technology (CBIT), Hyderabad",
  "Vasavi College of Engineering, Hyderabad",
  "VNR Vignana Jyothi Institute of Engineering and Technology (VNR VJIET), Hyderabad",
  "Gokaraju Rangaraju Institute of Engineering and Technology (GRIET), Hyderabad",
  "Osmania University College of Engineering (OUCE), Hyderabad",
  "JNTUH College of Engineering, Hyderabad",
  "Andhra University College of Engineering, Visakhapatnam",
  "K L Deemed to be University, Guntur",
  "Gitam Deemed University, Visakhapatnam",
  "SRKR Engineering College, Bhimavaram",
  "GMR Institute of Technology (GMRIT), Rajam",
  "JNTUK College of Engineering, Kakinada",
  "JNTUA College of Engineering, Anantapur",

  // West Bengal
  "Jadavpur University, Kolkata",
  "Institute of Engineering and Management (IEM), Kolkata",
  "Heritage Institute of Technology, Kolkata",
  "Techno India University, Kolkata",
  "Government College of Engineering and Leather Technology, Kolkata",
  "Kalyani Government Engineering College (KGEC), Kalyani",
  "Jalpaiguri Government Engineering College (JGEC), Jalpaiguri",
  "Indian Institute of Engineering Science and Technology (IIEST), Shibpur",
  "Haldia Institute of Technology, Haldia",

  // Other Major Institutes
  "Lovely Professional University (LPU), Jalandhar",
  "Thapar Institute of Engineering and Technology, Patiala",
  "Punjab Engineering College (PEC), Chandigarh",
  "Chandigarh University (CU), Mohali",
  "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar",
  "Siksha 'O' Anusandhan (ITER), Bhubaneswar",
  "Veer Surendra Sai University of Technology (VSSUT), Burla",
  "Birla Institute of Technology (BIT), Mesra, Ranchi",
  "Manipal Institute of Technology (MIT), Manipal",
  "Manipal University, Jaipur",
  "Sikkim Manipal Institute of Technology (SMIT), Sikkim",
  "The LNM Institute of Information Technology (LNMIIT), Jaipur",
  "Nirma University, Ahmedabad",
  "Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT), Gandhinagar",
  "Pandit Deendayal Energy University (PDEU), Gandhinagar",
  "Shri Govindram Seksaria Institute of Technology and Science (SGSITS), Indore",
  "Madhav Institute of Technology and Science (MITS), Gwalior",
  "Banaras Hindu University (BHU), Varanasi",
  "Aligarh Muslim University (AMU), Aligarh",
  "Jamia Millia Islamia (JMI), New Delhi",
  "Symbiosis Institute of Technology (SIT), Pune",
  "K L University, Hyderabad"
];
