/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api/verify-payment'
import { Route as ApiSendEmailRouteImport } from './routes/api/send-email'
import { Route as ApiCreateRazorpayOrderRouteImport } from './routes/api/create-razorpay-order'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateRazorpayOrderRoute = ApiCreateRazorpayOrderRouteImport.update({
  id: '/api/create-razorpay-order',
  path: '/api/create-razorpay-order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/api/create-razorpay-order': typeof ApiCreateRazorpayOrderRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/api/create-razorpay-order': typeof ApiCreateRazorpayOrderRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/api/create-razorpay-order': typeof ApiCreateRazorpayOrderRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/api/create-razorpay-order'
    | '/api/send-email'
    | '/api/verify-payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/api/create-razorpay-order'
    | '/api/send-email'
    | '/api/verify-payment'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/api/create-razorpay-order'
    | '/api/send-email'
    | '/api/verify-payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  ApiCreateRazorpayOrderRoute: typeof ApiCreateRazorpayOrderRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-razorpay-order': {
      id: '/api/create-razorpay-order'
      path: '/api/create-razorpay-order'
      fullPath: '/api/create-razorpay-order'
      preLoaderRoute: typeof ApiCreateRazorpayOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  ApiCreateRazorpayOrderRoute: ApiCreateRazorpayOrderRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
